language: python
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35

# Use container-based infrastrucutre
sudo: false

# command to install dependencies
install:
  - pip install coveralls
  - pip install tox

# command to run tests
script:
  tox

after_success:
  coveralls
